### PR TITLE
feat(add-cloud-masthead): add cloud test page

### PR DESCRIPTION
**Pull request by proeung**
### Related Ticket(s)

N/A

### Description

- This PR adds a test page that showcases the <dds-cloud-masthead-container> component.

### Changelog

**New**

- cloud-base.hbs - base handlebar template that doesn't depend on `<dds-dotcom-shell-container>` component.

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by annawen1** [comment]
hey @proeung can you take a look at the percy snapshot diffs?

**Comment by jeffchew** [comment]
> hey @proeung can you take a look at the percy snapshot diffs?

@annawen1 this was already noticed by some others before this PR, we aren't sure how this diff crept in.

**Comment by annawen1** [comment]
> > hey @proeung can you take a look at the percy snapshot diffs?
> 
> @annawen1 this was already noticed by some others before this PR, we aren't sure how this diff crept in.

oh ok, gotcha - I guess this is ready to go then?

**Comment by proeung** [comment]
Great! Let me know if you guys need anything. Here's the preview link for the Cloud test page - https://ibmdotcom-web-components-html-test.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/34/cloud/index.html

**Comment by proeung** [comment]
@jeffchew @annawen1 Any feedback regarding this PR?

**Comment by annawen1** [comment]
> @jeffchew @annawen1 Any feedback regarding this PR?

I'll go a head and merge this since the percy snapshots are something we're aware of

**Review by annawen1 — APPROVED** [review]

**Pull request merged**
