### PR TITLE
chore(components-test): recreated nextjs pages

### PR DESCRIPTION
**Pull request by IgnacioBecerra**
### Related Ticket(s)

#4 

### Description

Created the Learn, Solutions, and Services test pages from the NextJS version.

### Changelog

**New**

- added three pages using the Carbon for IBM.com web components

### CODE REVIEW

**Comment by jeffchew** [comment]
@IgnacioBecerra these look great!

The video player isn't working for me, at least on the solution page. Are you using videos that match the kaltura IDs that are being used?

**Comment by IgnacioBecerra** [comment]
@jeffchew Yeah, I'm using the IDs that were used in the NextJS page. Using the ID that was used in the Video Player storybook the videos are able to play. Not sure how the IDs currently used can fetch the thumbnail and eyebrow, but not the video itself 🤔

**Comment by IgnacioBecerra** [comment]
@jeffchew Ended up using the placeholder video ID from Storybook, and I also added some of the placeholder images Wonil provided.

**Comment by jeffchew** [comment]
Thanks @IgnacioBecerra ! 
The deploy preview isn't showing some of the imagery for some reason, might be a pathing thing?

**Review by jeffchew — APPROVED** [review]
Thank you @IgnacioBecerra !

**Pull request merged**
